# Generated by Django 5.0.6 on 2024-07-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')]),
        ),
    ]
