# Generated by Django 5.0.6 on 2024-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_oder_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phanloai',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
